import fs from 'node:fs/promises';
import crypto from 'node:crypto';

const root='D:/data_fusion';
const specs=[
  {
    file:'M7_Late_Fusion_Complete_Explainability.ipynb',
    markdown:`## Standardized modality proportion versus input crime\n\n### What is being measured?\n\nM7 has no gate. The comparable quantity is the **effective branch-output proportion**: the absolute static and dynamic branch outputs immediately before the final prediction bias are normalized to sum to one.\n\n### Why is it being measured?\n\nThis diagnostic shows whether the relative magnitude of the two late-fusion branch outputs changes with recent crime intensity. It is not a gate probability and is not causal feature importance.\n\n### How is it calculated?\n\nFor each node-time case, the notebook uses the existing \`static_effective_share = |o_s|/(|o_s|+|o_d|+\\epsilon)\`; the dynamic proportion is its complement. Cases are grouped into quantile bins of mean input crime, and bin means with a 95% normal-approximation interval are plotted.\n\n### Presentation interpretation\n\nThe x-axis is mean input crime across the dynamic lag features. The y-axis is normalized branch-output magnitude. Blue denotes the static branch and orange denotes the dynamic branch. Interpret the pattern as association at the final late-fusion layer, not as the percentage of prediction caused by each modality.`,
    code:`# Standardized comparison plot: M7 branch-output proportion versus input crime\nif "late_frame" not in globals():\n    late_frame = pd.read_csv(os.path.join(output_folder, "late_fusion_rich_explainability.csv"))\n\ndef _standardized_binned_proportion(frame, x_col, y_col, bins=12):\n    work = frame[[x_col, y_col]].replace([np.inf, -np.inf], np.nan).dropna().copy()\n    work["bin"] = pd.qcut(work[x_col], q=bins, duplicates="drop")\n    out = work.groupby("bin", observed=True).agg(\n        mean_x=(x_col, "mean"), mean_y=(y_col, "mean"),\n        std_y=(y_col, "std"), count=(y_col, "size")\n    ).reset_index(drop=True)\n    out["ci95"] = 1.96 * out["std_y"] / np.sqrt(out["count"].clip(lower=1))\n    return out\n\nsummary = _standardized_binned_proportion(late_frame, "input_crime", "static_effective_share")\nplt.figure(figsize=(10, 6))\nplt.plot(summary.mean_x, summary.mean_y, marker="o", linewidth=2.5, label="Static branch-output proportion")\nplt.plot(summary.mean_x, 1-summary.mean_y, marker="s", linestyle="--", linewidth=2.5, label="Dynamic branch-output proportion")\nplt.fill_between(summary.mean_x, summary.mean_y-summary.ci95, summary.mean_y+summary.ci95, alpha=.15)\nplt.xlabel("Mean input crime"); plt.ylabel("Normalized branch-output magnitude"); plt.ylim(0, 1)\nplt.title("M7 effective branch-output proportion vs input crime")\nplt.legend(); plt.grid(alpha=.2); plt.tight_layout()\nplt.savefig(os.path.join(output_folder, "late_fusion_effective_contribution_vs_crime.png"), dpi=300, bbox_inches="tight")\nplt.show()\nsummary.assign(dynamic_mean_y=1-summary.mean_y).to_csv(os.path.join(output_folder, "late_fusion_effective_contribution_vs_crime.csv"), index=False)`
  },
  {
    file:'M11_Gate_Scalar_Complete_Explainability.ipynb',
    markdown:`## Standardized effective gated activation proportion versus input crime\n\n### What is being measured?\n\nM11 Scalar uses separate global scalar coefficients for the self and neighbor pathways. For each pathway, **effective gated activation proportion** combines the learned coefficient with the magnitude of the corresponding static and dynamic activation vectors.\n\n### Why is it being measured?\n\nThe raw scalar coefficients are constant across all cases and therefore cannot vary with crime. Effective activation proportions can vary because activation magnitudes vary with the input and neighborhood context.\n\n### How is it calculated?\n\nFor each role, the L2 norm of the coefficient-weighted static component is divided by the sum of the static and dynamic component norms. The dynamic proportion is one minus the static proportion. Cases are grouped into quantile bins of mean input crime.\n\n### Presentation interpretation\n\nThe left panel shows the self pathway and the right panel shows the neighbor pathway. Blue represents static activation and orange represents dynamic activation. These are mechanistic activation-magnitude diagnostics, not causal shares of the final prediction.`,
    code:`# Standardized comparison plot: M11 Scalar effective gated activation versus input crime\nif "scalar_frame" not in globals():\n    scalar_frame = pd.read_csv(os.path.join(output_folder, "scalar_m11_rich_explainability.csv"))\n\ndef _standardized_binned_proportion(frame, x_col, y_col, bins=12):\n    work = frame[[x_col, y_col]].replace([np.inf, -np.inf], np.nan).dropna().copy()\n    work["bin"] = pd.qcut(work[x_col], q=bins, duplicates="drop")\n    out = work.groupby("bin", observed=True).agg(\n        mean_x=(x_col, "mean"), mean_y=(y_col, "mean"),\n        std_y=(y_col, "std"), count=(y_col, "size")\n    ).reset_index(drop=True)\n    out["ci95"] = 1.96 * out["std_y"] / np.sqrt(out["count"].clip(lower=1))\n    return out\n\nfig, axes = plt.subplots(1, 2, figsize=(14, 5.5), sharey=True)\nall_summaries=[]\nfor ax, (role, col) in zip(axes, [("Self", "self_effective_static_proportion"), ("Neighbor", "neighbor_effective_static_proportion")]):\n    summary = _standardized_binned_proportion(scalar_frame, "input_crime", col)\n    summary["role"] = role; summary["dynamic_mean_y"] = 1-summary.mean_y; all_summaries.append(summary)\n    ax.plot(summary.mean_x, summary.mean_y, marker="o", linewidth=2.5, label="Static activation proportion")\n    ax.plot(summary.mean_x, 1-summary.mean_y, marker="s", linestyle="--", linewidth=2.5, label="Dynamic activation proportion")\n    ax.fill_between(summary.mean_x, summary.mean_y-summary.ci95, summary.mean_y+summary.ci95, alpha=.15)\n    ax.set(title=f"{role} pathway", xlabel="Mean input crime", ylim=(0,1)); ax.grid(alpha=.2)\naxes[0].set_ylabel("Normalized activation magnitude"); axes[1].legend()\nfig.suptitle("M11 Scalar effective gated activation proportion vs input crime")\nplt.tight_layout(); plt.savefig(os.path.join(output_folder, "scalar_effective_activation_contribution_vs_crime.png"), dpi=300, bbox_inches="tight")\nplt.show()\npd.concat(all_summaries, ignore_index=True).to_csv(os.path.join(output_folder, "scalar_effective_activation_contribution_vs_crime.csv"), index=False)`
  },
  {
    file:'M33_Hierarchical_Fusion_Complete_Explainability.ipynb',
    markdown:`## Standardized occlusion-based branch share versus input crime\n\n### What is being measured?\n\nM33 has no modality gate, so GMU-style effective gated activation is **not applicable**. Its scientifically valid counterpart is the **occlusion-based branch share**, calculated from the absolute prediction change when each branch is removed individually.\n\n### Why is it being measured?\n\nThis diagnostic shows whether relative frozen-model sensitivity to the static and dynamic branches changes with recent crime intensity.\n\n### How is it calculated?\n\nFor each node-time case, the absolute static-branch occlusion effect is divided by the sum of the absolute static and dynamic occlusion effects. The dynamic share is the complement. The separate non-additive interaction term is not included in this two-way normalization and must be interpreted separately.\n\n### Presentation interpretation\n\nThe x-axis is mean input crime. The y-axis is normalized occlusion-based branch share. Blue denotes static-branch sensitivity and orange denotes dynamic-branch sensitivity. This quantity is not an activation magnitude and should not be described as a gate.`,
    code:`# Standardized comparison plot: M33 occlusion-based branch share versus input crime\nif "hierarchical_frame" not in globals():\n    hierarchical_frame = pd.read_csv(os.path.join(output_folder, "hierarchical_rich_explainability.csv"))\n\ndef _standardized_binned_proportion(frame, x_col, y_col, bins=12):\n    work = frame[[x_col, y_col]].replace([np.inf, -np.inf], np.nan).dropna().copy()\n    work["bin"] = pd.qcut(work[x_col], q=bins, duplicates="drop")\n    out = work.groupby("bin", observed=True).agg(\n        mean_x=(x_col, "mean"), mean_y=(y_col, "mean"),\n        std_y=(y_col, "std"), count=(y_col, "size")\n    ).reset_index(drop=True)\n    out["ci95"] = 1.96 * out["std_y"] / np.sqrt(out["count"].clip(lower=1))\n    return out\n\nsummary = _standardized_binned_proportion(hierarchical_frame, "input_crime", "static_effective_share")\nplt.figure(figsize=(10, 6))\nplt.plot(summary.mean_x, summary.mean_y, marker="o", linewidth=2.5, label="Static occlusion-based share")\nplt.plot(summary.mean_x, 1-summary.mean_y, marker="s", linestyle="--", linewidth=2.5, label="Dynamic occlusion-based share")\nplt.fill_between(summary.mean_x, summary.mean_y-summary.ci95, summary.mean_y+summary.ci95, alpha=.15)\nplt.xlabel("Mean input crime"); plt.ylabel("Normalized occlusion-based branch share"); plt.ylim(0, 1)\nplt.title("M33 occlusion-based branch share vs input crime")\nplt.legend(); plt.grid(alpha=.2); plt.tight_layout()\nplt.savefig(os.path.join(output_folder, "hierarchical_effective_contribution_vs_crime.png"), dpi=300, bbox_inches="tight")\nplt.show()\nsummary.assign(dynamic_mean_y=1-summary.mean_y).to_csv(os.path.join(output_folder, "hierarchical_effective_contribution_vs_crime.csv"), index=False)`
  }
];

for(const spec of specs){
  const path=`${root}/${spec.file}`;
  const nb=JSON.parse(await fs.readFile(path,'utf8'));
  const marker='Standardized modality proportion versus input crime';
  const already=nb.cells.some(c=>(c.source||[]).join('').includes(marker) || (c.source||[]).join('').includes('Standardized effective gated activation proportion versus input crime') || (c.source||[]).join('').includes('Standardized occlusion-based branch share versus input crime'));
  if(already){console.log(`Already present: ${spec.file}`);continue;}
  const id=()=>crypto.randomBytes(4).toString('hex');
  nb.cells.push({cell_type:'markdown',id:id(),metadata:{},source:spec.markdown.split(/(?<=\n)/)});
  nb.cells.push({cell_type:'code',execution_count:null,id:id(),metadata:{},outputs:[],source:spec.code.split(/(?<=\n)/)});
  await fs.writeFile(path,JSON.stringify(nb,null,1)+'\n','utf8');
  console.log(`Updated ${spec.file}`);
}
